[package]
name = "token-vesting"
version = "1.0.0"
authors = []

[addresses]
token_vesting = "0x4932d6b29b843e8a87555c6eba55770f42fca69aa01417da6872d62b6157d34e"
Std = "0x1"
aptos_std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
